// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoqZKbQysTvRWh4Udp9obZey-ICg5Fq7U',
    appId: '1:330682939615:web:e0fe05e8c835ba7f55d16a',
    messagingSenderId: '330682939615',
    projectId: 'jannatak-d9cb9',
    authDomain: 'jannatak-d9cb9.firebaseapp.com',
    storageBucket: 'jannatak-d9cb9.firebasestorage.app',
    measurementId: 'G-ZZ693G3HRV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4Oa_grygMxMmRdINc3_FNF-sQdtCiTQU',
    appId: '1:330682939615:android:c318b0edbb0d85fb55d16a',
    messagingSenderId: '330682939615',
    projectId: 'jannatak-d9cb9',
    storageBucket: 'jannatak-d9cb9.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2cb5ZZRl5xR2xqhwD_hFr3RRlMmsyGUk',
    appId: '1:330682939615:ios:1f721784758315f455d16a',
    messagingSenderId: '330682939615',
    projectId: 'jannatak-d9cb9',
    storageBucket: 'jannatak-d9cb9.firebasestorage.app',
    iosBundleId: 'com.jannataka.quranPremium',
  );
}
