// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_dIcJd9dBR0KtI_u4KTk41uoMx1_jUpM',
    appId: '1:782792340518:web:81f1b4860e56fb1deaa2e7',
    messagingSenderId: '782792340518',
    projectId: 'sakina-f534d',
    authDomain: 'sakina-f534d.firebaseapp.com',
    storageBucket: 'sakina-f534d.firebasestorage.app',
    measurementId: 'G-M2Q8J113EK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiwcHiJwtsvWMsekNpHsqyqVvsxIw3sVQ',
    appId: '1:782792340518:android:7f5173fdc5fc92b3eaa2e7',
    messagingSenderId: '782792340518',
    projectId: 'sakina-f534d',
    storageBucket: 'sakina-f534d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZuI2I7ta4psNYtW-W5z1YFllzCS905WQ',
    appId: '1:782792340518:ios:8e7cb4aa04015bb0eaa2e7',
    messagingSenderId: '782792340518',
    projectId: 'sakina-f534d',
    storageBucket: 'sakina-f534d.firebasestorage.app',
    iosBundleId: 'com.example.sakinaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZuI2I7ta4psNYtW-W5z1YFllzCS905WQ',
    appId: '1:782792340518:ios:8e7cb4aa04015bb0eaa2e7',
    messagingSenderId: '782792340518',
    projectId: 'sakina-f534d',
    storageBucket: 'sakina-f534d.firebasestorage.app',
    iosBundleId: 'com.example.sakinaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_dIcJd9dBR0KtI_u4KTk41uoMx1_jUpM',
    appId: '1:782792340518:web:40b949163b65b89beaa2e7',
    messagingSenderId: '782792340518',
    projectId: 'sakina-f534d',
    authDomain: 'sakina-f534d.firebaseapp.com',
    storageBucket: 'sakina-f534d.firebasestorage.app',
    measurementId: 'G-MYKXMT37RL',
  );
}
